- name: Install NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ npm_packages }}"
  tags:
    - first-run

- name: Upgrade all NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ npm_packages }}"
  tags:
    - upgrade-npm
