- name: "See if {{ item }} is in the Dock."
  command:
    cmd: "dockutil --find '{{ item }}'"
  register: dockitem_exists
  changed_when: false
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout

- name: Ensure Dock item {{ item }} is removed.
  command:
    cmd: |
      dockutil --remove '{{ item }}'
      {% if not ansible_loop.last %}--no-restart{% endif %}
  when: dockitem_exists.rc  == 0

- name: Pause for 7 seconds between dock changes.
  pause:
    seconds: 7
  when:
    - dockitem_exists.rc == 0
    - ansible_loop.last
