- name: Git personal email setup
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true
  tags: [ git-personal, first-run ]

- name: Git personal name setup
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  no_log: true
  tags: [ git-personal, first-run ]
