# yazi.toml
[manager]
show_hidden = true
ratio = [1, 2, 5]

[plugin]
prepend_previewers = [
  { mime = "{image,audio,video}/*", run = "mediainfo" },
  { mime = "application/x-subrip", run = "mediainfo" },
]
