env:
  global:
    - secure: k+j9L/43VUG2xRCe1rcoch/WpGqIqx+egV5cHtHJo3pjujLkTRQJVe6Jmbeg8mSxt8HZVwli4sDatTcxvBUyhZ1JFrnXVnc70Q7LvzfcMpMTUepT1Mx5A7d3Qg7l96459xRhgNcPbx4JnHMWT+tX+R1Bip2Z4otEgfUpun93NQ0=
language: rust
script:
  - cargo build -v
  - cargo doc --no-deps -v
  - mv target/doc doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
