#homebrew doesn't provide version control as a simple option across all packages -_-"
homebrew_formulas:
  - name: bat
  - name: eza
  - name: fd
  - name: ffmpeg
  - name: ffmpegthumbnailer
  - name: fzf
  - name: gh
  - name: git
  - name: luajit
  - name: mediainfo
  - name: neovim
  - name: pipx
  - name: powerlevel10k
  - name: ripgrep
  - name: tlrc
  - name: tmux
  - name: tree-sitter
  - name: yazi
  - name: yt-dlp
  - name: zoxide
  - name: zsh-autosuggestions
  - name: zsh-syntax-highlighting
  - name: bash
  - name: n
  - name: bitwarden-cli
  - name: dockutil

homebrew_casks:
  - name: adobe-acrobat-reader
  - name: aerospace
  - name: audacity
  - name: bitwarden
  - name: calibre
  - name: discord
  - name: firefox
  - name: font-hack-nerd-font
  - name: google-chrome
  - name: nikitabobko/tap/aerospace
  - name: inkscape
  - name: iterm2
  - name: karabiner-elements
  - name: keka
  - name: linearmouse
  - name: mactex
  - name: obsidian
  - name: qbittorrent
  - name: sioyek
  - name: spotify
  - name: steam
  - name: the-unarchiver
  - name: visual-studio-code
  - name: vlc
  - name: wezterm
  - name: whatsapp
  - name: zoom
